image_finetune: false

output_dir: "outputs"
sd_model_path: "data/models/sd/stable-diffusion-v1-5"

unet_additional_kwargs:
  use_inflated_groupnorm         : true
  unet_use_cross_frame_attention : false
  unet_use_temporal_attention    : false
  use_motion_module              : true
  motion_module_resolutions      : [ 1,2,4,8 ]
  motion_module_mid_block        : true
  motion_module_decoder_only:     false
  motion_module_type: Vanilla

  motion_module_kwargs:
    num_attention_heads                : 8
    num_transformer_block              : 1
    attention_block_types              : [ "Temporal_Self", "Temporal_Self" ]
    temporal_position_encoding         : true
    temporal_position_encoding_max_len : 32
    temporal_attention_dim_div         : 1
    zero_initialize                    : False
    rotary_position_encoding           : False
    rotary_max_freq                    : 48

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "linear"
  steps_offset:        1
  clip_sample:         false

train_data:
  # shards:          "s3://webvid-10m/val-shards.json"
  shards:            "pipe:aws s3 cp s3://webvid-10m/train/{00000..10727}.tar -"
  # shards:            "pipe:aws s3 cp s3://webvid-10m/val/{00000..00004}.tar -"
  # shards:            "pipe:aws s3 cp s3://webvid-10m/cow_test/00000.tar -"

  # csv_path:        "./data/test.csv"
  # video_folder:    "./data/videos"
  sample_size:     256
  target_fps:      12
  sample_n_frames: 32

  use_lion_optim: False
  use_ademamix:   True
  use_clipping: True
  adapter_lora_path: ""
  # adapter_lora_path: "data/models/motion-module/v3_sd15_adapter.ckpt"
  # adapter_lora_scale: 1


validation_data:
  shards:       "pipe:aws s3 cp s3://webvid-10m/val/{00000..00004}.tar -"
  val_size:     20
  sample_size:     256
  target_fps:      12
  sample_n_frames: 32

  prompts:
    - "Handheld shot of frustrated businesswoman in formalwear and face mask pushed to her chin sitting at desk in office during covid-19 outbreak. she is trying to call someone and reading documents"
    - "Two cows eating hay"
    - "b&w photo of 42 y.o man in black clothes, bald, face, half body, body, high detailed skin, skin pores, coastline, overcast weather, wind, waves, 8k uhd, dslr, soft lighting, high quality, film grain, Fujifilm XT3"
    - "close up photo of a rabbit, forest, haze, halation, bloom, dramatic atmosphere, centred, rule of thirds, 200mm 1.4f macro shot"
  num_inference_steps: 25
  guidance_scale: 8
  context_frames: 32
  context_stride: 1
  context_overlap: 4
  fps: 12
  seed: 123456

trainable_modules:
  - "motion_modules."

# resume_id: "zrypp7qf"
unet_checkpoint_path: "/workspace/animatediff-cli/256-shutterstock-sd1-5.pth"
# unet_checkpoint_path: "/workspace/animatediff-cli/training_ad-2024-09-10T01-20-08_animatediff.pth"
# unet_checkpoint_path: ""

min_snr_gamma:    5
loss_type:        "huber"
learning_rate:    1.e-5
lr_warmup_steps:  100
scale_lr:         -0.5
lr_scheduler:     "cosine"
# lr_scheduler:     "linear"
# lr_scheduler:     "cosine"
train_batch_size: 2
gradient_accumulation_steps: 2
num_workers: 4

# epoch_size:           10000000
# epoch_size:           10001
epoch_size:           100001
num_epochs:           1
checkpointing_epochs: -1
checkpointing_steps:  200

validation_steps:           20
validation_gen_steps:       200
validation_gen_steps_tuple: []

global_seed: 42
mixed_precision_training: False
enable_xformers_memory_efficient_attention: False
gradient_checkpointing: True

is_debug: False
