output_dir: "outputs"
sd_model_path: "C:/dev/VideoTraining/models/StableDiffusion"

train_data:
  # shards:          "s3://webvid-10m/val-shards.json"
  # shards:            "pipe:aws s3 cp s3://webvid-10m/val/{00000..00004}.tar -"
  shards:            "pipe:aws s3 cp s3://webvid-10m/test/00000.tar -"

  # csv_path:        "./data/test.csv"
  # video_folder:    "./data/videos"
  target_fps:      4
  sample_n_frames: 16

validation_data:
  prompts:
    - "b&w photo of 42 y.o man in black clothes, bald, face, half body, body, high detailed skin, skin pores, coastline, overcast weather, wind, waves, 8k uhd, dslr, soft lighting, high quality, film grain, Fujifilm XT3"
    - "close up photo of a rabbit, forest, haze, halation, bloom, dramatic atmosphere, centred, rule of thirds, 200mm 1.4f macro shot"
    - photo of coastline, rocks, storm weather, wind, waves, lightning, 8k uhd, dslr, soft lighting, high quality, film grain, Fujifilm XT3"
    - "night, b&w photo of old house, post apocalypse, forest, storm weather, wind, rocks, 8k uhd, dslr, soft lighting, high quality, film grain"
  num_inference_steps: 25
  guidance_scale: 7.5
  context_frames: 16
  context_stride: 1
  context_overlap: 4

learning_rate:    1.e-4
train_batch_size: 3
gradient_accumulation_steps: 1
num_workers: 22

epoch_size:           1000
num_epochs:           1
checkpointing_epochs: -1
checkpointing_steps:  1000

# validation_steps:       5000
validation_steps_tuple: [100, 1000]

global_seed: 42
mixed_precision_training: True
enable_xformers_memory_efficient_attention: False
gradient_checkpointing: False

is_debug: False
